# Generated by Django 4.2.6 on 2023-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_pdffilebe_pdffilebme_pdffilechem_pdffilemaths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.CharField(default='abcd', max_length=100),
        ),
    ]
